### PR TITLE
fix: get viewport size tag via Cypress.config or add it via options

### LINKED ISSUE #44: cypress TRACK_IMAGE task should send the actual viewport size
As seen here:
https://github.com/Visual-Regression-Tracker/agent-cypress/blob/65fa78d0a12cf8cb950fd21e466a03a02903d8ed/lib/plugin.js#L57

Viewport is just read one time from the initial config. But viewport size should be sent from the task because it can be dynamically changed.

More specifically, using this `Cypress.config('viewportWidth')` and `Cypress.config('viewportHeight')` 
here:
https://github.com/Visual-Regression-Tracker/agent-cypress/blob/65fa78d0a12cf8cb950fd21e466a03a02903d8ed/lib/commands.ts#L74

### PR DESCRIPTION
**Pull request by dekaravanhoc**
As I the current setup (Viewport tag is based on the config) is not really usable, I added the possibility to just add it in as an option or use Cypress.config as a default.

As I am not super firm with .ts and cypress codebase, this should be doublechecked.

closes #44

### CODE REVIEW

File: lib/utils.ts [hunk 1]
```diff
@@ -61,6 +61,7 @@ export const trackImage = (
           name,
           imageBase64,
           browser: Cypress.browser.name,
+          viewport: options?.viewport ? options.viewport : Cypress.config("viewportWidth") * pixelRatio + "x" + Cypress.config("viewportHeight") * pixelRatio,
```
Comment (pashidlos) [inline lib/utils.ts:64]: you could use `??` [operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)
```suggestion
          viewport: options?.viewport ?? `${Cypress.config("viewportWidth") * pixelRatio}x${Cypress.config("viewportHeight") * pixelRatio}`,
```

**Review by pashidlos — CHANGES_REQUESTED** [review]
please update as well options type here
https://github.com/Visual-Regression-Tracker/agent-cypress/blob/master/lib/index.ts#L39

and readme by adding new option 
https://github.com/Visual-Regression-Tracker/agent-cypress#assert

**Review by pashidlos — APPROVED** [review]
LGTM

**Comment by pashidlos** [comment]
@dekaravanhoc thanks for contribution!
